apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-server
  name: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-server
    spec:
      containers:
      - image: sample_api:latest
        name: sample-api
        resources: {}
        imagePullPolicy: Never
status: {}