apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    tier: front-end
spec:
  type: NodePort
  selector:
    app: myapp
    tier: front-end
  ports:
    - port: 80
      nodePort: 30009
      targetPort: 80
  
