apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    app: demo-voting-app
    name: voting-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
      app: demo-voting-app
      name: voting-app-deployment
